/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_Main.Distributors.SupplierDirectory;

import Business.EnterpriseFrame.Enterprise;
import Business.OrganizationFrame.Supplier_Org;
import Business.UserHaandle.UserHandle;
import Business_Frame.MainSystem;
import javax.swing.JPanel;

/**
 *
 * @author mynenidivya
 */
public class SupplierWorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierWorkPanel
     */
    public SupplierWorkPanel(JPanel userProcessContainer, UserHandle account, Supplier_Org par, Enterprise enterprise, MainSystem Business) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
