/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.DistributorsArea;

import Business.EmployeeArea.Employeeclass;
import Business.OrganizationFrame.Organization;
import Business.OrganizationFrame.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Validation.Validation;

/**
 *
 * @author admin
 */
public class DistributorManageEmployeePanel extends javax.swing.JPanel {

    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    
    /**
     * Creates new setup ManageOrganizationJPanel
     */
    public DistributorManageEmployeePanel(JPanel userProcessContainer,OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }
    
    public void populateOrganizationComboBox(){
        Org_JComboBox.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            Org_JComboBox.addItem(organization);
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        OrgEmp_JComboBox.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            OrgEmp_JComboBox.addItem(organization);
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) Org_JTable.getModel();
        
        model.setRowCount(0);
        
        for (Employeeclass employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[2];
            row[0] = employee.getId();
            row[1] = employee.getName();
            model.addRow(row);
        }
    }
    /**
     * To initialize the form,this method is invoked within the constructor
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Org_JTable = new javax.swing.JTable();
        addEmp_JButton = new javax.swing.JButton();
        Org_JComboBox = new javax.swing.JComboBox();
        lblOrganization = new javax.swing.JLabel();
        back_JButton = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        OrgEmp_JComboBox = new javax.swing.JComboBox();
        lblOrg1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Org_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Org_JTable);
        if (Org_JTable.getColumnModel().getColumnCount() > 0) {
            Org_JTable.getColumnModel().getColumn(0).setResizable(false);
            Org_JTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 63, 480, 92));

        addEmp_JButton.setText("Create Employee");
        addEmp_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmp_JButtonActionPerformed(evt);
            }
        });
        add(addEmp_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 315, -1, -1));

        Org_JComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Org_JComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Org_JComboBoxActionPerformed(evt);
            }
        });
        add(Org_JComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 34, 81, -1));

        lblOrganization.setText("Organization");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 37, -1, -1));

        back_JButton.setText("<< Back");
        back_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_JButtonActionPerformed(evt);
            }
        });
        add(back_JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 315, -1, -1));

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 229, -1, -1));

        nameJTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameJTextFieldKeyPressed(evt);
            }
        });
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 226, 126, -1));

        OrgEmp_JComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrgEmp_JComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrgEmp_JComboBoxActionPerformed(evt);
            }
        });
        add(OrgEmp_JComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 186, 120, -1));

        lblOrg1.setText("Organization");
        add(lblOrg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 189, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addEmp_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmp_JButtonActionPerformed
         if(!nameJTextField.getText().equals("")){
        Organization organization = (Organization) OrgEmp_JComboBox.getSelectedItem();
        String name = nameJTextField.getText();
        
        organization.getEmployeeDirectory().createEmployee(name);
         populateTable(organization);
        }else{
             JOptionPane.showMessageDialog(null, "Enter value", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_addEmp_JButtonActionPerformed

    private void back_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_JButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_back_JButtonActionPerformed

    private void Org_JComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Org_JComboBoxActionPerformed
        Organization organization = (Organization) Org_JComboBox.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    }//GEN-LAST:event_Org_JComboBoxActionPerformed

    private void nameJTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameJTextFieldKeyPressed
        // TODO add your handling code here:
        Validation.onlyString(evt, nameJTextField);
    }//GEN-LAST:event_nameJTextFieldKeyPressed

    private void OrgEmp_JComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrgEmp_JComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrgEmp_JComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox OrgEmp_JComboBox;
    private javax.swing.JComboBox Org_JComboBox;
    private javax.swing.JTable Org_JTable;
    private javax.swing.JButton addEmp_JButton;
    private javax.swing.JButton back_JButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrg1;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JTextField nameJTextField;
    // End of variables declaration//GEN-END:variables
}
