/*
 * AdminWorkPanel.java
 *
 * 
 */

package UI_Main.DistributorsArea;

import Business.EnterpriseFrame.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class DistributorWorkAreaPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new setup AdminWorkAreaJPanel */
    public DistributorWorkAreaPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
    }
    
    /** To initialize the form ,the method is invoked within the constructor.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWorkarea = new javax.swing.JLabel();
        WorkuserJButton = new javax.swing.JButton();
        ManageEmpJButton = new javax.swing.JButton();
        ManageOrgJButton = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWorkarea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWorkarea.setText(" Work Area -Adminstrative");
        add(lblWorkarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        WorkuserJButton.setText("User");
        WorkuserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkuserJButtonActionPerformed(evt);
            }
        });
        add(WorkuserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, -1));

        ManageEmpJButton.setText("Employee");
        ManageEmpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmpJButtonActionPerformed(evt);
            }
        });
        add(ManageEmpJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 150, -1));

        ManageOrgJButton.setText("Organization");
        ManageOrgJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageOrgJButtonActionPerformed(evt);
            }
        });
        add(ManageOrgJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 160, -1));

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise Name :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 170, 30));

        valueLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MicrosoftTeams-image (21).png"))); // NOI18N
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, 370));

        valueLabel1.setText("<value>");
        add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void WorkuserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkuserJButtonActionPerformed
        // TODO add your handling code here:
        DistributorManageUserPanel muajp = new DistributorManageUserPanel(userProcessContainer, enterprise);
        userProcessContainer.add("DistributorManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_WorkuserJButtonActionPerformed

    private void ManageEmpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmpJButtonActionPerformed

        DistributorManageEmployeePanel manageEmployeeJPanel = new DistributorManageEmployeePanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("DistributorManageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageEmpJButtonActionPerformed

    private void ManageOrgJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageOrgJButtonActionPerformed

        DistributorManageOrganization manageOrganizationJPanel = new DistributorManageOrganization(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("DistributorManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageOrgJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEmpJButton;
    private javax.swing.JButton ManageOrgJButton;
    private javax.swing.JButton WorkuserJButton;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblWorkarea;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    // End of variables declaration//GEN-END:variables
    
}
