/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.DistributorsArea;

import Business.Clinicarea.Doctor;
import Business.Clinicarea.PharmacyWork;
import Business_Frame.MainSystem;
import Business.EmployeeArea.Employeeclass;
import Business.EnterpriseFrame.Enterprise;
import Business.OrganizationFrame.Organization;
import Business.OrganizationFrame.Organization.Type;
import Business.OrganizationFrame.Provider_Org;
import Business.OrganizationFrame.Supplier_Org;
import Business.Role.PharmacyRole;
import Business.Role.ProviderRole;
import Business.Role.Roles;
import Business.Role.SupplierRole;
import Business.SupplierArea.Provider;
import Business.SupplierArea.Supplier;
import Business.UserHaandle.UserHandle;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DistributorManageUserPanel extends javax.swing.JPanel {

    /**
     * Creates new setup ManageUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;

    public DistributorManageUserPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;

        popOrganizationComboBox();
       // employeeJComboBox.removeAllItems();
        popData();
    }

    public void popOrganizationComboBox() {
        OrgUserJComboBox.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            OrgUserJComboBox.addItem(organization);
        }
    }
    
    public void populateEmployeeComboBox(Organization organization){
        Manage_employeeJComboBox.removeAllItems();
        
        for (Employeeclass employee : organization.getEmployeeDirectory().getEmployeeList()){
            Manage_employeeJComboBox.addItem(employee);
        }
    }
    
    private void populateRoleComboBox(Enterprise e){
        RoleJComboBox.removeAllItems();
        Organization organization = (Organization) OrgUserJComboBox.getSelectedItem();
        if(organization instanceof Supplier_Org){
       // for (Role role : e.getSupportedRole()){
            RoleJComboBox.addItem(new SupplierRole());
        }
        if(organization instanceof Provider_Org){
             RoleJComboBox.addItem(new ProviderRole());
        }
       // }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) ManageUserJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserHandle ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) ManageUserJTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * To initialize the form,the method is invoked within the constructor.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createUserJButton = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ManageUserJTable = new javax.swing.JTable();
        lblPassword = new javax.swing.JLabel();
        passwordJTextField = new javax.swing.JTextField();
        lblEmp = new javax.swing.JLabel();
        Manage_employeeJComboBox = new javax.swing.JComboBox();
        backjButton1 = new javax.swing.JButton();
        lblOrgUser = new javax.swing.JLabel();
        OrgUserJComboBox = new javax.swing.JComboBox();
        lblRole = new javax.swing.JLabel();
        RoleJComboBox = new javax.swing.JComboBox();
        lblUsername1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createUserJButton.setText("Create");
        createUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserJButtonActionPerformed(evt);
            }
        });
        add(createUserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 140, -1));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 146, -1));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setText("User Name");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        ManageUserJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ManageUserJTable);
        if (ManageUserJTable.getColumnModel().getColumnCount() > 0) {
            ManageUserJTable.getColumnModel().getColumn(0).setResizable(false);
            ManageUserJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 375, 179));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 146, -1));

        lblEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmp.setText("Employee");
        add(lblEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        Manage_employeeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(Manage_employeeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 146, -1));

        backjButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backjButton1.setText(" Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });
        add(backjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, 30));

        lblOrgUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrgUser.setText("Organization");
        add(lblOrgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        OrgUserJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OrgUserJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrgUserJComboBoxActionPerformed(evt);
            }
        });
        add(OrgUserJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 146, -1));

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRole.setText("Role");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 40, -1));

        RoleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(RoleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 146, -1));

        lblUsername1.setIcon(new javax.swing.ImageIcon("C:\\Users\\namra\\Downloads\\aed8.jpg")); // NOI18N
        add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 710, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void createUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserJButtonActionPerformed
        String userName = nameJTextField.getText();
        String password = passwordJTextField.getText();
         if(!((userName.equals("") || (password.equals(""))))){
        if(MainSystem.checkIfUsernameIsUnique(userName)){
        Organization organization = (Organization) OrgUserJComboBox.getSelectedItem();
        Employeeclass employee = (Employeeclass) Manage_employeeJComboBox.getSelectedItem();
        Roles role = (Roles) RoleJComboBox.getSelectedItem();
//        if (role instanceof SupplierRole){
//        Supplier organizations = new Supplier();
//        //enterprise.getOrganizationDirectory().createOrganization(Type.Sup);
//         organizations.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
//        }
//        else{
//           Provider  organizations = new Provider();
//            organizations.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
//              
//        }
        if (organization instanceof Supplier_Org){
           Supplier s= new Supplier();
            
           s.setSupplierName(employee.getName());
           ((Supplier_Org) organization).getSupplierList().getSupplierList().add(s);
          
        }
        if (organization instanceof Provider_Org){
           Provider p= new Provider();
            
           p.setProviderName(employee.getName());
           
           ((Provider_Org) organization).setProvider(p);
          
        }
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
        popData();
        }
        else{
           JOptionPane.showMessageDialog(null, "Please enter valid username", "Warning", JOptionPane.WARNING_MESSAGE); 
        }
        }else{
             JOptionPane.showMessageDialog(null, "Enter a value", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_createUserJButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void OrgUserJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrgUserJComboBoxActionPerformed
        Organization organization = (Organization) OrgUserJComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(enterprise);
        }
    }//GEN-LAST:event_OrgUserJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ManageUserJTable;
    private javax.swing.JComboBox Manage_employeeJComboBox;
    private javax.swing.JComboBox OrgUserJComboBox;
    private javax.swing.JComboBox RoleJComboBox;
    private javax.swing.JButton backjButton1;
    private javax.swing.JButton createUserJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblOrgUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField passwordJTextField;
    // End of variables declaration//GEN-END:variables
}
