/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.Hospital_class;

import UI_Main.AdministrativeWorkArea.*;
import Business.OrganizationFrame.Organization;
import Business.OrganizationFrame.Organization.Type;
import Business.OrganizationFrame.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class HospitalManageOrganizationPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    
    /**
     * Creates new setup ManageOrganizationJPanel
     */
    public HospitalManageOrganizationPanel(JPanel userProcessContainer,OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        
        populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        HospitalManageOrgJComboBox.removeAllItems();
      //  for (Type type : Organization.Type.values()){
       //     if (!type.getValue().equals(Type.Clinic.getValue()))
                HospitalManageOrgJComboBox.addItem(Type.Clinic);
      //  }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) HospitalManageOrgJTable.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
    /**
     * To initialize the form,the method is invoked within the constructor.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HospitalManageOrgJTable = new javax.swing.JTable();
        HospitalManageOrgaddJButton = new javax.swing.JButton();
        HospitalManageOrgJComboBox = new javax.swing.JComboBox();
        lblHospitalOrgType = new javax.swing.JLabel();
        HospitalManageOrgbackJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HospitalManageOrgJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(HospitalManageOrgJTable);
        if (HospitalManageOrgJTable.getColumnModel().getColumnCount() > 0) {
            HospitalManageOrgJTable.getColumnModel().getColumn(0).setResizable(false);
            HospitalManageOrgJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 480, 92));

        HospitalManageOrgaddJButton.setText("Add Clinic");
        HospitalManageOrgaddJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalManageOrgaddJButtonActionPerformed(evt);
            }
        });
        add(HospitalManageOrgaddJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        HospitalManageOrgJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(HospitalManageOrgJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 81, -1));

        lblHospitalOrgType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHospitalOrgType.setText("Organization Type ");
        add(lblHospitalOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        HospitalManageOrgbackJButton.setText(" Back");
        HospitalManageOrgbackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalManageOrgbackJButtonActionPerformed(evt);
            }
        });
        add(HospitalManageOrgbackJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\namra\\Downloads\\aed21.jpg")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void HospitalManageOrgaddJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalManageOrgaddJButtonActionPerformed

        Type type = (Type) HospitalManageOrgJComboBox.getSelectedItem();
        directory.createOrganization(type);
        populateTable();
    }//GEN-LAST:event_HospitalManageOrgaddJButtonActionPerformed

    private void HospitalManageOrgbackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalManageOrgbackJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_HospitalManageOrgbackJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox HospitalManageOrgJComboBox;
    private javax.swing.JTable HospitalManageOrgJTable;
    private javax.swing.JButton HospitalManageOrgaddJButton;
    private javax.swing.JButton HospitalManageOrgbackJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHospitalOrgType;
    // End of variables declaration//GEN-END:variables
}
