/*
 * AdminWork.java
 *
 */

package UI_Main.Hospital_class;

import UI_Main.AdministrativeWorkArea.*;
import Business.EnterpriseFrame.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  admin
 */
public class HospitalAdminPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public HospitalAdminPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
    }
    
    /**To initialize the form,the method is invoked within the constructor
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHospital = new javax.swing.JLabel();
        HospitalManageuserJButton = new javax.swing.JButton();
        HospitalManageEmployeeJButton = new javax.swing.JButton();
        HospitalManageOrgJButton = new javax.swing.JButton();
        lblHospitalenterprise = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHospital.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHospital.setText("Hospital Work Area -Adminstrative Role");
        add(lblHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        HospitalManageuserJButton.setText("Manage User");
        HospitalManageuserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalManageuserJButtonActionPerformed(evt);
            }
        });
        add(HospitalManageuserJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 150, -1));

        HospitalManageEmployeeJButton.setText("Manage Employee");
        HospitalManageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalManageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(HospitalManageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, -1));

        HospitalManageOrgJButton.setText("Manage Organization");
        HospitalManageOrgJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalManageOrgJButtonActionPerformed(evt);
            }
        });
        add(HospitalManageOrgJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        lblHospitalenterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHospitalenterprise.setText("Enterprise :");
        add(lblHospitalenterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void HospitalManageuserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalManageuserJButtonActionPerformed
        // TODO add your handling code here:
        HospitalManageUserPanel muajp = new HospitalManageUserPanel(userProcessContainer, enterprise);
        userProcessContainer.add("HospitalManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_HospitalManageuserJButtonActionPerformed

    private void HospitalManageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalManageEmployeeJButtonActionPerformed

        HospitalManageEmployeePanel manageEmployeeJPanel = new HospitalManageEmployeePanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("HospitalManageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_HospitalManageEmployeeJButtonActionPerformed

    private void HospitalManageOrgJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalManageOrgJButtonActionPerformed

        HospitalManageOrganizationPanel manageOrganizationJPanel = new HospitalManageOrganizationPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("HospitalManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_HospitalManageOrgJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HospitalManageEmployeeJButton;
    private javax.swing.JButton HospitalManageOrgJButton;
    private javax.swing.JButton HospitalManageuserJButton;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblHospitalenterprise;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
