/*
 * AdminWorkPanel.java
 *
 *
 */
package UI_Main.AdministrativeWorkArea;

import Business_Frame.MainSystem;
import Business.EnterpriseFrame.Enterprise;
import Business.NetworkArea.NetworkArea;
import Business.OrganizationFrame.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author admin
 */
public class AdminWorkPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    MainSystem sys;

    /**
     * Creates new form AdminWorkPanel
     */
    public AdminWorkPanel(JPanel userProcessContainer, MainSystem sys) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.sys = sys;

        populateTree();
    }

    public void populateTree() {
        
        DefaultTreeModel model = (DefaultTreeModel) treeSystem.getModel();

        
        
        ArrayList<NetworkArea> networkList = sys.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        NetworkArea networkarea;
        Enterprise enterprise;
        Organization organization;

        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        for (int i = 0; i < networkList.size(); i++) {
            networkarea = networkList.get(i);
            networkNode = new DefaultMutableTreeNode(networkarea.getName());
            networks.insert(networkNode, i);

            enterpriseList = networkarea.getEnterpriseDirectory().getEnterpriseList();

            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode, j);

                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }

        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlMainScreen = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        btnMngAdmin = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        lblSelectedNode = new javax.swing.JLabel();
        lblSelectedNodes = new javax.swing.JLabel();
        btnMngVaccineCatalog = new javax.swing.JButton();
        btnMngDiseaseCatalog = new javax.swing.JButton();
        btnGraph = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        pnlSystem = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeSystem = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);

        pnlMainScreen.setBackground(new java.awt.Color(255, 204, 204));
        pnlMainScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        pnlMainScreen.add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 179, -1));

        btnMngAdmin.setText("Manage Enterprise Admin");
        btnMngAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAdminActionPerformed(evt);
            }
        });
        pnlMainScreen.add(btnMngAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 180, -1));

        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        pnlMainScreen.add(btnManageEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 179, -1));

        lblSelectedNode.setText("Selected Node:");
        pnlMainScreen.add(lblSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        pnlMainScreen.add(lblSelectedNodes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, 40));

        btnMngVaccineCatalog.setText("Manage Vaccine Catalog");
        btnMngVaccineCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngVaccineCatalogActionPerformed(evt);
            }
        });
        pnlMainScreen.add(btnMngVaccineCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 180, -1));

        btnMngDiseaseCatalog.setText("Manage Disease Catalog");
        btnMngDiseaseCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngDiseaseCatalogActionPerformed(evt);
            }
        });
        pnlMainScreen.add(btnMngDiseaseCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 180, -1));

        btnGraph.setText("View Graphical Data");
        btnGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphActionPerformed(evt);
            }
        });
        pnlMainScreen.add(btnGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 180, -1));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 0, 51));
        lblHeading.setText("VACCINE SUPPLY MANAGEMENT CHAIN");
        pnlMainScreen.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 370, 30));

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhema\\Downloads\\MicrosoftTeams-image (2).png")); // NOI18N
        pnlMainScreen.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 200));

        jSplitPane1.setRightComponent(pnlMainScreen);

        pnlSystem.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        treeSystem.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeSystem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        treeSystem.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                valueChangedAction(evt);
            }
        });
        jScrollPane1.setViewportView(treeSystem);

        pnlSystem.add(jScrollPane1);

        jSplitPane1.setLeftComponent(pnlSystem);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed

        EnterprisePanel manageEnterpriseJPanel = new EnterprisePanel(userProcessContainer, sys);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnMngAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAdminActionPerformed
        // TODO add your handling code here:
        EnterpriseAdminPanel manageEnterpriseAdminJPanel = new EnterpriseAdminPanel(userProcessContainer, sys);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngAdminActionPerformed

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        NetworkPanel manageNetworkJPanel = new NetworkPanel(userProcessContainer, sys);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void valueChangedAction(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_valueChangedAction
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) treeSystem.getLastSelectedPathComponent();
        if (selectedNode != null) {
            lblSelectedNodes.setText(selectedNode.toString());
        }

    }//GEN-LAST:event_valueChangedAction

    private void btnMngVaccineCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngVaccineCatalogActionPerformed
        // TODO add your handling code here:
        VaccineDirectoryPanel manageNetworkJPanel = new VaccineDirectoryPanel(userProcessContainer, sys);
        userProcessContainer.add("ManageVaccineDirectoryJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngVaccineCatalogActionPerformed

    private void btnMngDiseaseCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngDiseaseCatalogActionPerformed
        // TODO add your handling code here:
         DiseaseDirectoryPanel manageNetworkJPanel = new DiseaseDirectoryPanel(userProcessContainer, sys);
        userProcessContainer.add("ManageDiseaseDirectoryJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngDiseaseCatalogActionPerformed

    private void btnGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphActionPerformed

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(400, "VaccineCount", "Supplier");
                dataset.setValue(200, "VaccineCount", "Distributer");
                        dataset.setValue(100, "VaccineCount", "Pharma");
                        JFreeChart chart = ChartFactory.createBarChart("VaccinationTrend", "VaccinationSystem", "Number of Vaccinations",dataset,PlotOrientation.VERTICAL,false,true,false);
                        CategoryPlot p = chart.getCategoryPlot();
                        p.setRangeGridlinePaint(Color.black);
                        ChartFrame frame = new ChartFrame(" Vaccination trend in the system",chart);
                        frame.setVisible(true);
                        frame.setSize(450,300);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGraphActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraph;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnMngAdmin;
    private javax.swing.JButton btnMngDiseaseCatalog;
    private javax.swing.JButton btnMngVaccineCatalog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblSelectedNode;
    private javax.swing.JLabel lblSelectedNodes;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlSystem;
    private javax.swing.JTree treeSystem;
    // End of variables declaration//GEN-END:variables
}
