/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.AdministrativeWorkArea;



import Business.C2D.Disease;
import Business_Frame.MainSystem;
import Business.SupplierArea.Vaccine;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Validation.Validation;

/**
 *
 * @author Administrator
 */
public class DiseaseDirectoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form for DiseaseDirectoryPanel
     */
   private JPanel userProcessContainer;
   private MainSystem businesses;
 
    public DiseaseDirectoryPanel(JPanel userProcessContainer, MainSystem businesses){
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.businesses=businesses;
        populateDiseaseTable();
    }
    public void populateDiseaseTable(){
         DefaultTableModel dtm= (DefaultTableModel) tblDiseaseID.getModel();
       dtm.setRowCount(0);
       for (Disease disease : businesses.getDiseaseList().getDiseaseList()) {
           Object[] row = new Object[2];
           row[0]= disease;
           row[1]=disease.getDiseaseId();
           dtm.addRow(row);
       }  
       }
    

    /**
     * This method is called from within the constructor to generate the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiseaseID = new javax.swing.JTable();
        btnCreateDisease = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        btnDeleteDisease = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        tfieldDiseaseName = new javax.swing.JTextField();
        lblDiseaseDirectory = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDiseaseID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disease Name", "Disease ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDiseaseID);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 120, 590, 170));

        btnCreateDisease.setText("Create New Disease");
        btnCreateDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDiseaseActionPerformed(evt);
            }
        });
        add(btnCreateDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 150, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblwelcome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 240, 20));

        btnDeleteDisease.setText("Delete Disease");
        btnDeleteDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDiseaseActionPerformed(evt);
            }
        });
        add(btnDeleteDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 180, -1));

        lblCreate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblCreate.setText("Create Disease ");
        add(lblCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 170, 30));

        tfieldDiseaseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfieldDiseaseNameKeyPressed(evt);
            }
        });
        add(tfieldDiseaseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 120, -1));

        lblDiseaseDirectory.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblDiseaseDirectory.setText("Manage Disease Directory");
        add(lblDiseaseDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 320, 30));

        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDiseaseActionPerformed
        // TODO add your handling code here:
         if(!tfieldDiseaseName.getText().equals("")){
        Disease v= businesses.getDiseaseList().addDisease();
        v.setDiseaseName(tfieldDiseaseName.getText());
        populateDiseaseTable();
         }else{
             JOptionPane.showMessageDialog(null, "Enter value", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        
    }//GEN-LAST:event_btnCreateDiseaseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDiseaseActionPerformed
        // TODO add your handling code here:
          int selectedRow= tblDiseaseID.getSelectedRow();
         if(selectedRow<0){
             JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
      }
        else{
             
         Disease p=(Disease) tblDiseaseID.getValueAt(selectedRow, 0);

         businesses.getDiseaseList().removeDisease(p);
          JOptionPane.showMessageDialog(null, "You have successfully deleted the account");
        populateDiseaseTable();
         }
         
    }//GEN-LAST:event_btnDeleteDiseaseActionPerformed

    private void tfieldDiseaseNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfieldDiseaseNameKeyPressed
        // TODO add your handling code here:
        Validation.onlyString(evt, tfieldDiseaseName);
    }//GEN-LAST:event_tfieldDiseaseNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateDisease;
    private javax.swing.JButton btnDeleteDisease;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDiseaseDirectory;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JTable tblDiseaseID;
    private javax.swing.JTextField tfieldDiseaseName;
    // End of variables declaration//GEN-END:variables
}
