/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.AdministrativeWorkArea;

import Business_Frame.MainSystem;
import Business.EnterpriseFrame.Enterprise;
import Business.NetworkArea.NetworkArea;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Validation.Validation;

/**
 *
 * @author admin
 */
public class EnterprisePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private MainSystem sys;

    /**
     * Creates new form for ManageEnterprisePanel
     */
    public EnterprisePanel(JPanel userProcessContainer, MainSystem sys) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.sys = sys;

        populateTable();
        populateComboBox();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEnterprise.getModel();

        model.setRowCount(0);
        for (NetworkArea networkarea : sys.getNetworkList()) {
            for (Enterprise enterprise : networkarea.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise;
                row[1] = networkarea.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }

    private void populateComboBox() {
        comboxNetwork.removeAllItems();
        comboxEnterpriseType.removeAllItems();

        for (NetworkArea networkarea : sys.getNetworkList()) {
            comboxNetwork.addItem(networkarea);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            comboxEnterpriseType.addItem(type);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lblNetwork = new javax.swing.JLabel();
        comboxNetwork = new javax.swing.JComboBox();
        lblName = new javax.swing.JLabel();
        tfieldName = new javax.swing.JTextField();
        lblEnterpriseType = new javax.swing.JLabel();
        comboxEnterpriseType = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnDeleteReq = new javax.swing.JButton();
        lblEnterprisePanel = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 523, 95));

        lblNetwork.setForeground(new java.awt.Color(255, 255, 255));
        lblNetwork.setText("Network");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        comboxNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxNetworkActionPerformed(evt);
            }
        });
        add(comboxNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 136, -1));

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        tfieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldNameActionPerformed(evt);
            }
        });
        tfieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfieldNameKeyPressed(evt);
            }
        });
        add(tfieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 136, -1));

        lblEnterpriseType.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseType.setText("Enterprise Type");
        add(lblEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        comboxEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxEnterpriseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxEnterpriseTypeActionPerformed(evt);
            }
        });
        add(comboxEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 136, -1));

        btnSubmit.setText("Create Enterprise");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        btnDeleteReq.setText("Delete request");
        btnDeleteReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReqActionPerformed(evt);
            }
        });
        add(btnDeleteReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        lblEnterprisePanel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEnterprisePanel.setText("Manage Enterprise Panel");
        add(lblEnterprisePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaccine-story-knowledge-enterprise_1170x625px.jpg"))); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if(!tfieldName.getText().equals("")){
        NetworkArea networkarea = (NetworkArea) comboxNetwork.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) comboxEnterpriseType.getSelectedItem();

        if (networkarea == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = tfieldName.getText();
        
        Enterprise enterprise = networkarea.getEnterpriseDirectory().createAndAddEnterprise(name, type);

        populateTable();
         }else{
             JOptionPane.showMessageDialog(null, "Enter a valid value", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkPanel sysAdminwjp = (AdminWorkPanel) component;
        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReqActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblEnterprise.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select atleast one row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            Enterprise p=(Enterprise) tblEnterprise.getValueAt(selectedRow, 0);

            for (NetworkArea networkarea : sys.getNetworkList()) {
                for (Enterprise enterprise : networkarea.getEnterpriseDirectory().getEnterpriseList()) {
                   
                        if(p==enterprise){
                           networkarea.getEnterpriseDirectory().getEnterpriseList().remove(p);
                            break;
                        }

                    
                }
            }

            JOptionPane.showMessageDialog(null, "Account deleted successfully");
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteReqActionPerformed

    private void tfieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfieldNameKeyPressed
        // TODO add your handling code here:
        Validation.onlyString(evt, tfieldName);
    }//GEN-LAST:event_tfieldNameKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void tfieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldNameActionPerformed

    private void comboxEnterpriseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxEnterpriseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxEnterpriseTypeActionPerformed

    private void comboxNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxNetworkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxNetworkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteReq;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboxEnterpriseType;
    private javax.swing.JComboBox comboxNetwork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprisePanel;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField tfieldName;
    // End of variables declaration//GEN-END:variables
}
