/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.AdministrativeWorkArea;

import Business_Frame.MainSystem;
import Business.NetworkArea.NetworkArea;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Validation.Validation;

/**
 *
 * @author admin
 */
public class NetworkPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private MainSystem sys;

    /**
     *
     * Creates new form for ManageNetworkJPanel
     */
    public NetworkPanel(JPanel userProcessContainer, MainSystem sys) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.sys = sys;

        populateNetworkTable();
    }

    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) tblNetworkName.getModel();

        model.setRowCount(0);
        for (NetworkArea networkarea : sys.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = networkarea;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetworkName = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        tfieldName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblNetwork = new javax.swing.JLabel();
        btnDeleteReq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNetworkName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNetworkName);
        if (tblNetworkName.getColumnModel().getColumnCount() > 0) {
            tblNetworkName.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 404, 91));

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        btnSubmit.setText("Create Network");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        tfieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldNameActionPerformed(evt);
            }
        });
        tfieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfieldNameKeyPressed(evt);
            }
        });
        add(tfieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 93, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNetwork.setText("Manage Network Panel");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 310, 30));

        btnDeleteReq.setText("Delete Network");
        btnDeleteReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteReqActionPerformed(evt);
            }
        });
        add(btnDeleteReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frame-0019.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 700, 550));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String name = tfieldName.getText();
        if(!name.equals("")){
        NetworkArea networkarea = sys.createAndAddNetwork();
        networkarea.setName(name);

        populateNetworkTable();
         }else{
             JOptionPane.showMessageDialog(null, "Warning","Please enter a value", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkPanel sysAdminwjp = (AdminWorkPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteReqActionPerformed
        // TODO add your handling code here:
        int selectedRow= tblNetworkName.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            NetworkArea p=(NetworkArea) tblNetworkName.getValueAt(selectedRow, 0);

            for (NetworkArea networkarea : sys.getNetworkList()) {
                    if(p==networkarea){
                      sys.getNetworkList().remove(p);
                        break;
                    }
            }

            JOptionPane.showMessageDialog(null, "Account deleted successfully");
            populateNetworkTable();
        }
    }//GEN-LAST:event_btnDeleteReqActionPerformed

    private void tfieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfieldNameKeyPressed
        // TODO add your handling code here:
        Validation.onlyString(evt, tfieldName);
    }//GEN-LAST:event_tfieldNameKeyPressed

    private void tfieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteReq;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JTable tblNetworkName;
    private javax.swing.JTextField tfieldName;
    // End of variables declaration//GEN-END:variables
}
