/*
 * AdminWorkPanel.java
 *
 * 
 */

package UI_Main.C2D;

import Business_Frame.MainSystem;
import Business.EnterpriseFrame.Enterprise;
import Business.OrganizationFrame.C2DManagerOrganization;
import Business.OrganizationFrame.Organization;
import Business.UserHaandle.UserHandle;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class C2DAdminWork_Space extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
  MainSystem businesses;
    /** Creates new form AdminWorkAreaJPanel */
    public C2DAdminWork_Space(JPanel userProcessContainer, Enterprise enterprise, MainSystem businesses) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.businesses=businesses;
    
        lblValue.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWorkArea = new javax.swing.JLabel();
        btnManageUser = new javax.swing.JButton();
        btnManageEmployee = new javax.swing.JButton();
        btnManageOrg = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnCatalog = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWorkArea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWorkArea.setText("My Work Area -Adminstrative Role");
        add(lblWorkArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnManageUser.setText("Manage User");
        btnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserActionPerformed(evt);
            }
        });
        add(btnManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 150, -1));

        btnManageEmployee.setText("Manage Employee");
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });
        add(btnManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, -1));

        btnManageOrg.setText("Manage Organization");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });
        add(btnManageOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        btnCatalog.setBackground(new java.awt.Color(255, 255, 204));
        btnCatalog.setText("View Catalog");
        btnCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogActionPerformed(evt);
            }
        });
        add(btnCatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserActionPerformed
        // TODO add your handling code here:
        CDCManageUserHandlePanel muajp = new CDCManageUserHandlePanel(userProcessContainer, enterprise);
        userProcessContainer.add("CDCManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageUserActionPerformed

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed

        C2DManageemployeePanel manageEmployeeJPanel = new C2DManageemployeePanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("CDCManageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed

        CDCManageorganizationPanel manageOrganizationJPanel = new CDCManageorganizationPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("CDCManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOrgActionPerformed

    private void btnCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogActionPerformed
        // TODO add your handling code here:
        C2D_CatalogPanel manageOrganizationJPanel = new C2D_CatalogPanel(userProcessContainer, businesses);
        userProcessContainer.add("CDCCatalogJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCatalogActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalog;
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnManageUser;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblValue;
    private javax.swing.JLabel lblWorkArea;
    // End of variables declaration//GEN-END:variables
    
}
