/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.C2D;

import Business.EmployeeArea.Employeeclass;
import Business.OrganizationFrame.Organization;
import Business.OrganizationFrame.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Validation.Validation;

/**
 *
 * @author admin
 */
public class C2DManageemployeePanel extends javax.swing.JPanel {

    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public C2DManageemployeePanel(JPanel userProcessContainer,OrganizationDirectory organizationDir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        
        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }
    
    public void populateOrganizationComboBox(){
        comboxOrg.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            comboxOrg.addItem(organization);
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        comboxEmp.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            comboxEmp.addItem(organization);
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) tblIdName.getModel();
        
        model.setRowCount(0);
        
        for (Employeeclass employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[2];
            row[0] = employee.getId();
            row[1] = employee.getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIdName = new javax.swing.JTable();
        btnCreateEmp = new javax.swing.JButton();
        comboxOrg = new javax.swing.JComboBox();
        lblOrg = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        tfieldName = new javax.swing.JTextField();
        comboxEmp = new javax.swing.JComboBox();
        lblOrganization = new javax.swing.JLabel();
        lblManageEmployee = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblIdName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblIdName);
        if (tblIdName.getColumnModel().getColumnCount() > 0) {
            tblIdName.getColumnModel().getColumn(0).setResizable(false);
            tblIdName.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 480, 92));

        btnCreateEmp.setText("Create Employee");
        btnCreateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmpActionPerformed(evt);
            }
        });
        add(btnCreateEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        comboxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxOrgActionPerformed(evt);
            }
        });
        add(comboxOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 81, -1));

        lblOrg.setText("Organization");
        add(lblOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        tfieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldNameActionPerformed(evt);
            }
        });
        tfieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfieldNameKeyPressed(evt);
            }
        });
        add(tfieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 126, -1));

        comboxEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboxEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, -1));

        lblOrganization.setText("Organization");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 76, -1, -1));

        lblManageEmployee.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblManageEmployee.setText("Manage Employee Details");
        add(lblManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 220, 30));

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhema\\Downloads\\MicrosoftTeams-image.png")); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmpActionPerformed
         if(!tfieldName.getText().equals("")){
        Organization organization = (Organization) comboxEmp.getSelectedItem();
        String name = tfieldName.getText();
        
        organization.getEmployeeDirectory().createEmployee(name);
         populateTable(organization);
         }else{
             JOptionPane.showMessageDialog(null, "Enter a valid value", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnCreateEmpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboxOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxOrgActionPerformed
        Organization organization = (Organization) comboxOrg.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    }//GEN-LAST:event_comboxOrgActionPerformed

    private void tfieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfieldNameKeyPressed
        // TODO add your handling code here:
        Validation.onlyString(evt, tfieldName);
    }//GEN-LAST:event_tfieldNameKeyPressed

    private void tfieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateEmp;
    private javax.swing.JComboBox comboxEmp;
    private javax.swing.JComboBox comboxOrg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblManageEmployee;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JTable tblIdName;
    private javax.swing.JTextField tfieldName;
    // End of variables declaration//GEN-END:variables
}
