/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Main.C2D;

import Business_Frame.MainSystem;
import Business.EmployeeArea.Employeeclass;
import Business.EnterpriseFrame.Enterprise;
import Business.OrganizationFrame.Organization;
import Business.Role.Roles;
import Business.UserHaandle.UserHandle;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class CDCManageUserHandlePanel extends javax.swing.JPanel {

    /**
     * Creates new form for ManageUserAccountPanel
     */
    private JPanel container;
    private Enterprise enterprise;

    public CDCManageUserHandlePanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        this.container = container;

        popOrganizationComboBox();
       // employeeJComboBox.removeAllItems();
        popData();
    }

    public void popOrganizationComboBox() {
        comboxOrg.removeAllItems();

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            comboxOrg.addItem(organization);
        }
    }
    
    public void populateEmployeeComboBox(Organization organization){
        comboxEmployee.removeAllItems();
        
        for (Employeeclass employee : organization.getEmployeeDirectory().getEmployeeList()){
            comboxEmployee.addItem(employee);
        }
    }
    
    private void populateRoleComboBox(Enterprise e){
        comboxRole.removeAllItems();
        for (Roles role : e.getSupportedRole()){
            comboxRole.addItem(role);
        }
    }

    public void popData() {

        DefaultTableModel model = (DefaultTableModel) tblUser.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserHandle ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) tblUser.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateUser = new javax.swing.JButton();
        tfieldUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        lblPassword = new javax.swing.JLabel();
        tfiledPassword = new javax.swing.JTextField();
        lblEmployee = new javax.swing.JLabel();
        comboxEmployee = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        lblOrg = new javax.swing.JLabel();
        comboxOrg = new javax.swing.JComboBox();
        lblRole = new javax.swing.JLabel();
        comboxRole = new javax.swing.JComboBox();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        tfieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldUsernameActionPerformed(evt);
            }
        });
        add(tfieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 200, -1));

        lblUsername.setText("User Name");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUser);
        if (tblUser.getColumnModel().getColumnCount() > 0) {
            tblUser.getColumnModel().getColumn(0).setResizable(false);
            tblUser.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 375, 179));

        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        add(tfiledPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 200, -1));

        lblEmployee.setText("Employee");
        add(lblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        comboxEmployee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxEmployeeActionPerformed(evt);
            }
        });
        add(comboxEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        btnBack.setText(" Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 20));

        lblOrg.setText("Organization");
        add(lblOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        comboxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxOrgActionPerformed(evt);
            }
        });
        add(comboxOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, -1));

        lblRole.setText("Role");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        comboxRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxRoleActionPerformed(evt);
            }
        });
        add(comboxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, -1));

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\bhema\\Downloads\\MicrosoftTeams-image.png")); // NOI18N
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 610, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        String userName = tfieldUsername.getText();
        String password = tfiledPassword.getText();
          if(!((userName.equals("") || (password.equals(""))))){
        if(MainSystem.checkIfUsernameIsUnique(userName)){
        Organization organization = (Organization) comboxOrg.getSelectedItem();
        Employeeclass employee = (Employeeclass) comboxEmployee.getSelectedItem();
        Roles role = (Roles) comboxRole.getSelectedItem();
        
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
        
        popData();
        }else{
           JOptionPane.showMessageDialog(null, "Please enter a distinct username", "Warning", JOptionPane.WARNING_MESSAGE); 
        }
          }else{
             JOptionPane.showMessageDialog(null, "Enter a value", "Warning", JOptionPane.WARNING_MESSAGE);
        }
 
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboxOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxOrgActionPerformed
        Organization organization = (Organization) comboxOrg.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(enterprise);
        }
    }//GEN-LAST:event_comboxOrgActionPerformed

    private void tfieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldUsernameActionPerformed

    private void comboxEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxEmployeeActionPerformed

    private void comboxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxRoleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox comboxEmployee;
    private javax.swing.JComboBox comboxOrg;
    private javax.swing.JComboBox comboxRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField tfieldUsername;
    private javax.swing.JTextField tfiledPassword;
    // End of variables declaration//GEN-END:variables
}
